#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Quizard.Resource", IsApplication=true)]

namespace Quizard
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int error = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int FIFTYP = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int High80P = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Low40P = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Low50P = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Low80P = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int splashscreen512 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int splashScreenWatch = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int success = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int watchbackground = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int WN1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int WN2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int WN3 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int WN4 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int WN5 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int WN6 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int WN7 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ZEROP = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int AnswerCorrect = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int AnswerIncorrect = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int AnswerTextBox = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int AnswerTitle = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int QuestionNext = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int QuestionTextBox = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int QuestionTitle = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int QuizList = 2131034117;
			
			// aapt resource value: 0x7f050011
			public const int ResultAcceptButton = 2131034129;
			
			// aapt resource value: 0x7f05000b
			public const int ResultAverageTitle = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int ResultBackGround = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int ResultCancelButton = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int ResultEmoji = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int ResultPageTitle = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int ResultPercentage = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int ResultRetryTitle = 2131034126;
			
			// aapt resource value: 0x7f050014
			public const int SplashScreenImage = 2131034132;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050013
			public const int linearLayout2 = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int linearLayout3 = 2131034127;
			
			// aapt resource value: 0x7f050009
			public const int myButton = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AnswerFlashCard = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CardSets = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int QuestionFlashCard = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RectangleMain = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ResultsFlashCard = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RoundMain = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SplashScreen = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int hello_rect = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello_round = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
