#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Quizard.Resource", IsApplication=true)]

namespace Quizard
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int menuItems = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Cancel = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cardIconSmall = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Create = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Delete = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Edit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int EditTextStyle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int flashcard = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Home_Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int HomeICON = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int homepageIcon_small = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int play_icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int plusIcon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int QuizardLogo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int quizIcon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Settings = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int StartIcon = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int CardDeleteButtonID = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int CardEditButtonID = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int DeckAddCardCancelButton = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int DeckAddCardSaveButton = 2131165192;
			
			// aapt resource value: 0x7f070041
			public const int PlaySetFront_ViewAnswerButton = 2131165249;
			
			// aapt resource value: 0x7f07003e
			public const int PlaySetQuestionTextView = 2131165246;
			
			// aapt resource value: 0x7f07000b
			public const int QuestionAnswerTextViewID = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int QuestionEditText = 2131165189;
			
			// aapt resource value: 0x7f070033
			public const int addToFlashSetListButtonID = 2131165235;
			
			// aapt resource value: 0x7f07001d
			public const int answerTextBox = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int answerTextView = 2131165212;
			
			// aapt resource value: 0x7f07002a
			public const int cancelImageButtonID = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int cancelTextViewID = 2131165227;
			
			// aapt resource value: 0x7f07000e
			public const int cardDialogEditTextID = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int cardDialogTextViewID = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int cardFlipButtonID = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int cardTabAddButton = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int cardTabHomeButton = 2131165202;
			
			// aapt resource value: 0x7f070019
			public const int cardTabListView = 2131165209;
			
			// aapt resource value: 0x7f070014
			public const int cardTabPlayButton = 2131165204;
			
			// aapt resource value: 0x7f070011
			public const int cardTabToolbar = 2131165201;
			
			// aapt resource value: 0x7f070028
			public const int createAFlashSetImageButtonID = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int createAFlashSetTextViewID = 2131165225;
			
			// aapt resource value: 0x7f07003c
			public const int createAnAccountButtonID = 2131165244;
			
			// aapt resource value: 0x7f070003
			public const int createNewAccountButtonID = 2131165187;
			
			// aapt resource value: 0x7f070016
			public const int deckAddCardAnswerEditTextID = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int deckAddCardQuestionEditTextID = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int deckAddToDeckButtonID = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int deckDoneAddCardButtonID = 2131165208;
			
			// aapt resource value: 0x7f07001f
			public const int deckTextView = 2131165215;
			
			// aapt resource value: 0x7f07002e
			public const int deleteFlashSetImageButtonID = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int deleteFlashSetTextViewID = 2131165231;
			
			// aapt resource value: 0x7f07002c
			public const int editFlashSetSubjectImageButtonID = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int editFlashSetSubjectTextViewID = 2131165229;
			
			// aapt resource value: 0x7f070007
			public const int editText2 = 2131165191;
			
			// aapt resource value: 0x7f070036
			public const int enterIntoSelectedFlashSetButtonID = 2131165238;
			
			// aapt resource value: 0x7f070035
			public const int flashSetListViewID = 2131165237;
			
			// aapt resource value: 0x7f070032
			public const int flashSetSubjectEditTextID = 2131165234;
			
			// aapt resource value: 0x7f07001e
			public const int fragmentContainer = 2131165214;
			
			// aapt resource value: 0x7f07003b
			public const int loginButtonID = 2131165243;
			
			// aapt resource value: 0x7f07003d
			public const int loginProgressBarID = 2131165245;
			
			// aapt resource value: 0x7f070037
			public const int loginViewLinearLayoutID = 2131165239;
			
			// aapt resource value: 0x7f070002
			public const int newUserConfirmPasswordEditTextID = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int newUserPasswordEditTextID = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int newUserUsernameEditTextID = 2131165184;
			
			// aapt resource value: 0x7f070020
			public const int nextCardButton = 2131165216;
			
			// aapt resource value: 0x7f070040
			public const int playSetNoButton = 2131165248;
			
			// aapt resource value: 0x7f07003f
			public const int playSetYesButton = 2131165247;
			
			// aapt resource value: 0x7f07001b
			public const int questionTextBox = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int questionTextView = 2131165210;
			
			// aapt resource value: 0x7f070024
			public const int quizDialobNextButton = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int quizDialogRedoButton = 2131165219;
			
			// aapt resource value: 0x7f070022
			public const int quizRightWrongTextView = 2131165218;
			
			// aapt resource value: 0x7f070026
			public const int quizTabAnswerListView = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int quizTabNextButtonID = 2131165223;
			
			// aapt resource value: 0x7f070025
			public const int quizTabQuestionTextView = 2131165221;
			
			// aapt resource value: 0x7f07003a
			public const int rememberMeCheckBoxID = 2131165242;
			
			// aapt resource value: 0x7f070034
			public const int searchFlashSetsSearchViewID = 2131165236;
			
			// aapt resource value: 0x7f070030
			public const int settingsImageButtonID = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int settingsTextViewID = 2131165233;
			
			// aapt resource value: 0x7f070004
			public const int textView1 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int textView2 = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int toolbar1 = 2131165194;
			
			// aapt resource value: 0x7f070039
			public const int userLoginPasswordEditTextID = 2131165241;
			
			// aapt resource value: 0x7f070038
			public const int userLoginUsernameEditTextID = 2131165240;
			
			// aapt resource value: 0x7f070021
			public const int viewAnswerButton = 2131165217;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateAnAccountDialogLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DeckAddCardLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DeckCardDialogBox = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DeckCardTab = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DeckCardTabEditLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DeckLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int deckPlayLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int DeckQuizDialogBox = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int DeckQuizTab = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int HomeLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int LoginLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PlaySetLayout_Back = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int PlaySetLayout_Front = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CustomActionToolbarTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int HomeActionBar = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ListViewStyle_Light = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
